uri: "mongodb+srv://estate1.fosbavf.mongodb.net/?authSource=%24external&authMechanism=MONGODB-X509&retryWrites=true&w=majority"
tls: true
tlsCertificateKeyFile: "certs/svc_001.pem"
serverApiVersion: "1"
db: "real_estate_monitoring_rawdata"
collection: "properties"